[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "graphichetti"
version = "0.1.0"
description = "Libreria NLP per la generazione e modifica dinamica di grafici in italiano"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "scipy",
    "torch",
    "transformers",
    "huggingface_hub",
    "sentencepiece"
]

[tool.setuptools.packages.find]
where = ["."]